In [2]:
# imports
import torch
from torch import nn
import torch.optim as optim
from torchvision import transforms
from torchvision.datasets import MNIST # Training dataset
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# obtain mnist data and process
batch_size = 128
num_of_classes = 10

def get_indices(dataset,ind_array):
    indices =  []
    for i in range(len(dataset.targets)):
        for ind in ind_array:
            if dataset.targets[i] == ind:
                indices.append(i)
    return indices

dataset = MNIST('.', train=True, download=False,transform=transforms.ToTensor())
idx = get_indices(dataset, np.arange(num_of_classes))
data_loader_test = DataLoader(dataset, batch_size=batch_size, sampler = SubsetRandomSampler(idx))

classes = np.arange(num_of_classes)

In [7]:
for img,lbl in data_loader_test:
    print(torch.min(img).detach(),torch.max(img).detach())

tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.)

tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.) tensor(1.)
tensor(0.)

In [23]:
criterion=nn.BCEWithLogitsLoss()

In [43]:
fakepred = torch.rand(10,1)
fake_label = torch.zeros_like(fakepred)
lossF = criterion(fakepred,fake_label)

realpred = torch.rand(10,1)
real_label = torch.ones_like(realpred)
lossR = criterion(realpred,real_label)

disc_loss = 0.5*(lossF + lossR)
print(disc_loss)

tensor(0.7463)


In [45]:
criterion(torch.rand(10,1),torch.rand(10,1))

tensor(0.6889)

In [46]:
-torch.log(torch.sigmoid(torch.zeros(1)))

tensor([0.6931])

In [50]:
criterion(fake_label,fake_label)

tensor(0.6931)

In [59]:
tar_criterion=nn.CrossEntropyLoss()

In [99]:
preds = torch.rand(1000,5)
tar = torch.from_numpy(np.random.randint(2, size=1000))
tar_criterion(preds,tar)

tensor(1.6391)

In [128]:
c = .2
pert = torch.rand((3,1,4,4))
t = torch.norm(torch.norm(pert,2,-1),2,-1) # could also do frobenius norm 'fro'
C = torch.full(t.shape, c)
diff = t-C
hinge_loss = torch.mean( torch.max(diff,torch.zeros(diff.shape)) )

In [12]:
# comparing to noisy data 
imgs_noisey = torch.rand(128,28*28) + 0.25*torch.rand(128,28*28)

# model output
rf_output_clean = torch.rand(128)
nn_output_clean = torch.rand(128)
rf_output_adv = torch.rand(128)
nn_output_adv = torch.rand(128)
    
# # calculate and return accuracy 
# acc_rf_clean = accuracy_score(rf_output_clean,actual_lables)
# acc_nn_clean = accuracy_score(nn_output_clean.cpu().detach().numpy(),actual_lables)
# acc_rf_adv = accuracy_score(rf_output_adv,actual_lables)
# acc_nn_adv = accuracy_score(nn_output_adv.cpu().detach().numpy(),actual_lables)

# print('rf accuracy (clean): ', acc_rf_clean)
# print('nn accuracy (clean): ', acc_nn_clean)
# print('% adv rf: ', 1.-acc_rf_adv)
# print('% adv nn: ', 1.-acc_nn_adv)


In [14]:
nn_output_adv[rf_output_clean != nn_output_clean]

tensor([0.4768, 0.5956, 0.1290, 0.2718, 0.5799, 0.1799, 0.4614, 0.6201, 0.3596,
        0.7912, 0.9995, 0.4843, 0.5644, 0.9633, 0.3290, 0.3427, 0.6147, 0.6928,
        0.9551, 0.0778, 0.9429, 0.4803, 0.6511, 0.7452, 0.2137, 0.3196, 0.1509,
        0.0067, 0.5432, 0.0456, 0.7924, 0.4186, 0.8525, 0.5221, 0.4453, 0.5653,
        0.2650, 0.4624, 0.2129, 0.1841, 0.2024, 0.7199, 0.9694, 0.9968, 0.5124,
        0.7521, 0.7087, 0.5162, 0.7047, 0.9184, 0.3673, 0.0585, 0.3029, 0.9747,
        0.3508, 0.5380, 0.8177, 0.5450, 0.4133, 0.1430, 0.0975, 0.8122, 0.4355,
        0.2898, 0.8787, 0.0802, 0.0456, 0.5841, 0.3029, 0.2801, 0.5657, 0.1965,
        0.8499, 0.5490, 0.4241, 0.8070, 0.6314, 0.9673, 0.6634, 0.8277, 0.8922,
        0.2655, 0.5425, 0.5674, 0.3923, 0.1686, 0.3952, 0.3018, 0.0986, 0.2248,
        0.7407, 0.3140, 0.7604, 0.2926, 0.2217, 0.8733, 0.0312, 0.7593, 0.5419,
        0.8061, 0.0318, 0.2471, 0.9279, 0.9418, 0.5450, 0.6962, 0.9401, 0.8342,
        0.4633, 0.0717, 0.2517, 0.2260, 

In [18]:
X = np.array([20,30,15])
preds = torch.from_numpy(np.array([1,0,1]))
labels = torch.from_numpy(np.array([1,1,1]))

X[preds != labels]

array([30])

In [23]:
float(sum(labels == preds).detach().numpy())

2.0

In [26]:
torch.normal(0,1,preds.shape)

tensor([-0.4806, -0.9914,  0.1470])